name: CI-swarm
on:
  push: 
    branches: [master]
jobs: 
  swarm: 
    env:
      mode: swarm
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      run: |

        set -x

        project=$(basename $GITHUB_REPOSITORY)

        date=$(date +%s)

        docker build -t $GITHUB_REPOSITORY:$mode-$date --no-cache .
        #docker push $GITHUB_REPOSITORY:$mode-testing
      
        compose=etc/docker/$mode/$project.yaml        
        sed -i s/latest/$mode-$date/ $compose
        sudo cp -rv run/* /run        

        #Para Swarm
        docker swarm init
        sed -i s/worker/manager/ $compose        
        
        docker stack deploy -c $compose $project
        sudo rm -rfv /run/configs/$project
        sudo rm -rfv /run/secrets/$project
        
        while true
          do
            sleep 1
            docker service ls
            docker service ls | grep '\([0-9]\)/\1' && break
          done
